language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - composer self-update

install:
  - composer create-project laravel/laravel
  - cd ./laravel
  - composer require "molovo/laravel-model-traits:${TRAVIS_BRANCH}@dev"
  - composer update

before_script:
  - cp ./vendor/molovo/laravel-model-traits/.env.travis .env
  - export APP_ENV="testing"
  - php artisan migrate -q -n --path ./vendor/molovo/laravel-model-traits/src/migrations

script: vendor/bin/phpunit --verbose